Name: Kajol Tanesh Shah
Student ID: A20496724
Course no: CS512
Semester: Spring 2022

In [15]:
import numpy as np
import pandas as pd
import math

In [58]:
#QA - 1
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
c = np.array([[-1, 1, 3]])
print("2a - b :", np.subtract(2*a, b))

2a - b : [[-2]
 [-1]
 [ 0]]


In [61]:
#QA - 2
sq_a = np.square(a)
mag_a = np.sqrt(np.sum(sq_a))
print(mag_a)
a_cap = a/mag_a
print("a^ :", a_cap)
#mag_a = np.sqrt

3.7416573867739413
a^ : [[0.26726124]
 [0.53452248]
 [0.80178373]]


In [71]:
#QA - 3
x = np.array([[1, 0, 0]])
a_T = a.T
#print(np.dot(x, a_T))
cos = np.dot(x, a)/mag_a
print(cos)
print("Theta : ", math.acos(cos))

[[0.26726124]]
Theta :  1.3002465638163236


In [72]:
#QA - 4
dir_cosines = a/mag_a
print(cos_a)

[[0.26726124 0.53452248 0.80178373]]


In [76]:
#QA - 5
sq_b = np.square(b)
mag_b = np.sqrt(np.sum(sq_b))
print(mag_b)
ab_cos = np.dot(a_T, b)/(mag_a * mag_b)
print("cos theta :", ab_cos)

8.774964387392123
cos theta : [[0.97463185]]


In [78]:
#QA - 6
b_T = b.T
ab_dot = np.dot(a_T, b)
ba_dot = np.dot(b_T, a)
print("AB dot product :", ab_dot)
print("BA dot product :", ba_dot)


AB dot product : [[32]]
BA dot product : [[32]]


In [81]:
#QA - 8

acapb_dot = np.dot(a_cap.T, b)
sq_acap = np.square(a_cap)
mag_acap = np.sqrt(np.sum(sq_acap))
print(mag_acap)
print("Scalar proj of b onto a cap :", acapb_dot/mag_acap)

1.0
Scalar proj of b onto a cap : [[8.55235974]]


In [132]:
#QA - 9
#G = np.array([[0], [0], [0]])
#print(np.linalg.solve(G, a))

In [84]:
#QA - 10
ab_cross = np.cross(a_T, b_T)
ba_cross = np.cross(b_T, a_T)
print(ab_cross)
print(ba_cross)
sq_ab = np.square(ab_cross)
mag_ab = np.sqrt(np.sum(sq_ab))
print("magnitude of cross product ab: ",mag_ab)
sq_ba = np.square(ba_cross)
mag_ba = np.sqrt(np.sum(sq_ba))
print("magnitude of cross product ba: ",mag_ba)

[[-3  6 -3]]
[[ 3 -6  3]]
magnitude of cross product ab:  7.3484692283495345
magnitude of cross product ba:  7.3484692283495345


In [100]:
#QA - 12

new_mat = np.array([[1, 2, 3], [4, 5, 6], [-1, 1, 3]])
print(new_mat)
print(new_mat.shape)
deter = np.linalg.det(new_mat)
print("determinant is :",int(deter))

[[ 1  2  3]
 [ 4  5  6]
 [-1  1  3]]
(3, 3)
determinant is : 0


In [86]:
#QA - 13
ab_dot = np.dot(a, b_T)
print(a.shape)
ba_dot = np.dot(a_T, b)
print("AB dot product :", ab_dot)
print("BA dot product :", ba_dot)


(3, 1)
AB dot product : [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
BA dot product : [[32]]


In [90]:
#QB - 1
A = np.array([[1, 2, 3], [4, -2, 3], [0, 5, -1]])
print(A)
B = np.array([[1, 2, 1], [2, 1, -4], [3, -2, 1]])
print(B)
C = np.array([[1, 2, 3], [4, 5, 6], [-1, 1, 3]])
print(C)
d = np.array([[1], [2], [3]])
print(d)
print("2A - B :", np.subtract(2*A, B))

[[ 1  2  3]
 [ 4 -2  3]
 [ 0  5 -1]]
[[ 1  2  1]
 [ 2  1 -4]
 [ 3 -2  1]]
[[ 1  2  3]
 [ 4  5  6]
 [-1  1  3]]
[[1]
 [2]
 [3]]
2A - B : [[ 1  2  5]
 [ 6 -5 10]
 [-3 12 -3]]


In [91]:
#QB - 2
AB_dot = np.dot(A, B)
print("AB dot :", AB_dot)
BA_dot = np.dot(B, A)
print("BA dot :", BA_dot)

AB dot : [[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]
BA dot : [[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]


In [94]:
#QB - 3
print("AB transpose", AB_dot.T)
BTAT = np.dot(B.T, A.T)
print("B transpose . A transpose", BTAT)

AB transpose [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]
B transpose . A transpose [[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


In [99]:
#QB - 4
det_A = np.linalg.det(A)
print(det_A)
det_B = np.linalg.det(B)
print(det_B)
det_C = np.linalg.det(C)
print(int(det_C))

#QB - 5
#Row vectors of C are linearly dependent, A and B are not
#Row vectors of C form an orthogonal set

54.999999999999964
-42.00000000000002
0


In [101]:
#QB - 6
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)
print("A inverse :", A_inv)
print("B_inverse :", B_inv)

A inverse : [[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]]
B_inverse : [[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]


In [102]:
#QB - 7
C_inv = np.linalg.inv(C)
print("C inverse :", C_inv)

C inverse : [[ 1.20095990e+16 -4.00319967e+15 -4.00319967e+15]
 [-2.40191980e+16  8.00639934e+15  8.00639934e+15]
 [ 1.20095990e+16 -4.00319967e+15 -4.00319967e+15]]


In [103]:
#QB - 8 
Ad_dot = np.dot(A, d)
print("Ad dot :", Ad_dot)

Ad dot : [[14]
 [ 9]
 [ 7]]


In [104]:
#QB - 9
sq_d = np.square(d)
mag_d = np.sqrt(np.sum(sq_d))
print(mag_d)

3.7416573867739413


In [107]:
a1 = np.array([[1, 2, 3]])
a2 = np.array([[4, -2, 3]])
a3 = np.array([[0, 5, -1]])
#print(np.dot(d, a1))
proj_a1 = np.dot(a1, d)/mag_d
proj_a2 = np.dot(a2, d)/mag_d
proj_a3 = np.dot(a3, d)/mag_d
print(proj_a1)
print(proj_a2)
print(proj_a3)

[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[3.74165739]]
[[2.40535118]]
[[1.87082869]]


In [110]:
#QB - 10
#sq_mag_d = np.square(mag_d)
val_a1 = proj_a1/mag_d
val_a2 = proj_a2/mag_d
val_a3 = proj_a3/mag_d

In [111]:
print("vector proj of a1 on d :", val_a1*a1 )
print("vector proj of a2 on d :", val_a2*a2 )
print("vector proj of a3 on d :", val_a3*a3 )

vector proj of a1 on d : [[1. 2. 3.]]
vector proj of a2 on d : [[ 2.57142857 -1.28571429  1.92857143]]
vector proj of a3 on d : [[ 0.   2.5 -0.5]]


In [133]:
#QB - 12
#G = np.array([[1], [2], [3]])
print(np.linalg.solve(B, d))

[[ 1.00000000e+00]
 [ 2.37904934e-17]
 [-1.18952467e-17]]


In [136]:
#QB -13
print(np.linalg.solve(C, d))

[[-8.00639934e+15]
 [ 1.60127987e+16]
 [-8.00639934e+15]]


In [112]:
#QC - 1
D = np.array([[1, 2],[3, 2]])
E = np.array([[2, -2],[-2, 5]])
F = np.array([[1, 2], [2, 4]])
print("Eigen values and vectors of D :", np.linalg.eig(D))

Eigen values and vectors of D : (array([-1.,  4.]), array([[-0.70710678, -0.5547002 ],
       [ 0.70710678, -0.83205029]]))


In [116]:
#QC - 2
D_eigv1 = np.array([[-0.70710678, -0.5547002 ]])
D_eigv2 = np.array([[0.70710678, -0.83205029]])
print("Dot product of eig vectors of D: ", np.dot(D_eigv1, D_eigv2.T))

Dot product of eig vectors of D:  [[-0.03846154]]


In [117]:
#QC - 3
print("Eigen values and vectors of D :", np.linalg.eig(E))


Eigen values and vectors of D : (array([1., 6.]), array([[-0.89442719,  0.4472136 ],
       [-0.4472136 , -0.89442719]]))


In [118]:
E_eigv1 = np.array([[-0.89442719,  0.4472136 ]])
E_eigv2 = np.array([[-0.4472136 , -0.89442719]])
print("Dot product of eig vectors of E: ", np.dot(E_eigv1, E_eigv2.T))

Dot product of eig vectors of E:  [[0.]]


In [ ]:
#QC - 4 
#As dot product of eigen vectors of E is 0, the eigen vectorsof E are orthogonalb

In [129]:
#QC - 5 and 6
#G = np.array([[0], [0]])
#print(np.linalg.solve(F, G))

In [ ]:
#As the determinant of F is 0 i.e. it is a singular matrix so x = 0

In [128]:
#QC - 7
G = np.array([[0], [0]])
print(np.linalg.solve(D, G))

[[0.]
 [0.]]


In [ ]:
#It is has single solution which is x = 0 